[build-system]
requires = ["briefcase"]

[tool.briefcase]
project_name = "EddingtonGUI"
bundle = "com.eddington_gui"
version = "0.0.2.dev3"
url = "https://eddington_gui.com/eddington_gui"
license = "Apache Software License"
author = 'Sagi Shadur'
author_email = "saroad2@gmail.com"

[tool.briefcase.app.eddington_gui]
formal_name = "EddingtonGUI"
description = "A gui library wrapping Eddington"
icon = "src/eddington_gui/resources/eddington_gui"
sources = ['src/eddington_gui']
requires = [
    '--pre',
    'xlrd>=1.2.0',
    'eddington-core>=0.0.5.dev6',
    'eddington-fit>=0.0.1.dev3',
    'eddington-matplotlib>=0.0.5.dev5',
    'wxPython>=4.0.7'
]


[tool.briefcase.app.eddington_gui.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev18',
]

[tool.briefcase.app.eddington_gui.linux]
requires = [
    'toga-gtk>=0.3.0.dev18',
]

[tool.briefcase.app.eddington_gui.windows]
requires = [
    'toga-winforms>=0.3.0.dev18',
]

# Mobile deployments
[tool.briefcase.app.eddington_gui.iOS]
requires = [
    'toga-iOS>=0.3.0.dev18',
]

[tool.briefcase.app.eddington_gui.android]
requires = [
    'toga-android>=0.3.0.dev18',
]
