version: 2.1

jobs:
  style:
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - run:
          name: Update pip
          command: |
            python -m pip install --user --upgrade pip
            pip install flake8 black --user
      - run:
          name: Run black
          command: |
            $HOME/.local/bin/black $HOME/project/src --check
      - run:
          name: Run flake8
          command: |
            $HOME/.local/bin/flake8 --exclude=$HOME/project/src/eddington/__init__.py $HOME/project/src --max-line-length=88
            $HOME/.local/bin/flake8 --ignore=F403,F401 $HOME/project/src/__init__.py --max-line-length=88

workflows:
  main:
    jobs:
      - style
