version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  style:
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - run:
          name: Update pip
          command: |
            python -m pip install --user --upgrade pip
            pip install flake8 black --user
      - run:
          name: Run black
          command: |
            $HOME/.local/bin/black $HOME/project/src --check
      - run:
          name: Run flake8
          command: |
            $HOME/.local/bin/flake8 $HOME/project/src --max-line-length=88
  build:
    executor:
      name: win/default # executor type
      size: "medium"
    steps:
      - checkout
      - run:
          name: Install briefcase
          command: |
            pip install briefcase --user
      - run:
          name: Install Wix Toolset
          command: |
            Start-Process wpr -verb runAs -Args "-start GeneralProfile"
            choco install wixtoolset -y
      - restore_cache:
          keys:
            - windows-{{ checksum "pyproject.toml" }}
      - run:
          name: Briefcase create
          command: |
            python -m briefcase create --no-input
      - run:
          name: Briefcase update
          command: |
            python -m briefcase update
      - run:
          name: Briefcase package
          command: |
            python -m briefcase package
      - save_cache:
          paths:
            - windows
          key: windows-{{ checksum "pyproject.toml" }}
      - persist_to_workspace:
          root: ~/
          paths:
            - project/windows/*.msi
  publish:
    docker:
      - image: circleci/golang:1.14-buster
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: "Publish Release on GitHub"
          command: |
            go get github.com/tcnksm/ghr
            VERSION=v$(cat VERSION)
            ls /tmp/workspace
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} /tmp/workspace

workflows:
  main:
    jobs:
    - style
    - build:
        requires:
          - style
    - publish:
        requires:
          - build
