version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  style:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - run:
          name: run black
          command: |
            pip install back --user
            black src --check
      - python/save-cache

workflows:
  main:
    jobs:
      - build-and-test
